### PR TITLE
style: set the video title height on the video card

### PR DESCRIPTION
**Pull request by huzhongyang**
#894

### CODE REVIEW

**Comment by hakadao** [comment]
it seems werid... can you clearly explain why we should do that? for me.

**Comment by huzhongyang** [comment]
Hi, Some titles are one line and some are two lines, which causes the area below to be misaligned. I previously thought this was a style error. So I set a fixed height for the video title. 🤔

**Comment by hakadao** [comment]
> Hi, Some titles are one line and some are two lines, which causes the area below to be misaligned. I previously thought this was a style error. So I set a fixed height for the video title. 🤔

youtube doesn't handle this problem, i think the current design is already very good. This is not even a bug

**Comment by huzhongyang** [comment]
OK, I see. Thank you for review. 🙏

**Pull request closed without merging**
