### PR TITLE
adaptation `video-pod__list`

### PR DESCRIPTION
**Pull request by ljt990218**
#### Light Style
Light Style

#### Dark Style
Dark Style

### CODE REVIEW

**Comment by hakadao** [comment]
感謝，不過這個最好單獨分離出來放在下面目錄裏面吧，英文可以先隨便起個名作為樣式檔檔名
https://github.com/BewlyBewly/BewlyBewly/tree/main/src%2Fstyles%2FadaptedStyles%2FthirdParty

**Comment by hakadao** [comment]
> 感謝，不過這個最好單獨分離出來放在下面目錄裏面吧，英文可以先隨便起個名作為樣式檔檔名
> https://github.com/BewlyBewly/BewlyBewly/tree/main/src%2Fstyles%2FadaptedStyles%2FthirdParty

然後記得在這裏引用下，十分感謝
https://github.com/BewlyBewly/BewlyBewly/blob/main/src%2Fstyles%2FadaptedStyles%2Findex.ts

**Comment by ljt990218** [comment]
> 感謝，不過這個最好單獨分離出來放在下面目錄裏面吧，英文可以先隨便起個名作為樣式檔檔名 [`main`/src%2Fstyles%2FadaptedStyles%2FthirdParty](https://github.com/BewlyBewly/BewlyBewly/tree/main/src%2Fstyles%2FadaptedStyles%2FthirdParty)

修改好了 名字我真随便起了一个 想不到很好的

**Comment by hakadao** [comment]
如果只是改 `background-color` 別用 `background` 改

**Pull request merged**
